program: train.py
name: sweep
project: my_awesome_project
method: bayes
metric:
  goal: minimize
  name: validation_loss
parameters:
  lr:
    min: 0.0001
    max: 0.1
    distribution: log_uniform
  batch_size:
    values: [16, 32, 64]
  epochs:
    values: [5, 10, 15]
run_cap: 10

